//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoClientesWeb.ClienteApi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        private System.Nullable<int> Id_Tipo_ClienteField;
        
        private System.Nullable<int> Id_Situacao_ClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SituacaoField, value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> Id_Tipo_Cliente {
            get {
                return this.Id_Tipo_ClienteField;
            }
            set {
                if ((this.Id_Tipo_ClienteField.Equals(value) != true)) {
                    this.Id_Tipo_ClienteField = value;
                    this.RaisePropertyChanged("Id_Tipo_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> Id_Situacao_Cliente {
            get {
                return this.Id_Situacao_ClienteField;
            }
            set {
                if ((this.Id_Situacao_ClienteField.Equals(value) != true)) {
                    this.Id_Situacao_ClienteField = value;
                    this.RaisePropertyChanged("Id_Situacao_Cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tipo_Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Tipo_Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> Id_Tipo_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Id_Tipo_Cliente {
            get {
                return this.Id_Tipo_ClienteField;
            }
            set {
                if ((this.Id_Tipo_ClienteField.Equals(value) != true)) {
                    this.Id_Tipo_ClienteField = value;
                    this.RaisePropertyChanged("Id_Tipo_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Situacao_Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Situacao_Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> Id_Situacao_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> Id_Situacao_Cliente {
            get {
                return this.Id_Situacao_ClienteField;
            }
            set {
                if ((this.Id_Situacao_ClienteField.Equals(value) != true)) {
                    this.Id_Situacao_ClienteField = value;
                    this.RaisePropertyChanged("Id_Situacao_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteApi.CadastroSoap")]
    public interface CadastroSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ListaResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lista", ReplyAction="*")]
        ProjetoClientesWeb.ClienteApi.ListaResponse Lista(ProjetoClientesWeb.ClienteApi.ListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Lista", ReplyAction="*")]
        System.IAsyncResult BeginLista(ProjetoClientesWeb.ClienteApi.ListaRequest request, System.AsyncCallback callback, object asyncState);
        
        ProjetoClientesWeb.ClienteApi.ListaResponse EndLista(System.IAsyncResult result);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cpfCli no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaUnica", ReplyAction="*")]
        ProjetoClientesWeb.ClienteApi.ListaUnicaResponse ListaUnica(ProjetoClientesWeb.ClienteApi.ListaUnicaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ListaUnica", ReplyAction="*")]
        System.IAsyncResult BeginListaUnica(ProjetoClientesWeb.ClienteApi.ListaUnicaRequest request, System.AsyncCallback callback, object asyncState);
        
        ProjetoClientesWeb.ClienteApi.ListaUnicaResponse EndListaUnica(System.IAsyncResult result);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ListaTiposResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaTipos", ReplyAction="*")]
        ProjetoClientesWeb.ClienteApi.ListaTiposResponse ListaTipos(ProjetoClientesWeb.ClienteApi.ListaTiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ListaTipos", ReplyAction="*")]
        System.IAsyncResult BeginListaTipos(ProjetoClientesWeb.ClienteApi.ListaTiposRequest request, System.AsyncCallback callback, object asyncState);
        
        ProjetoClientesWeb.ClienteApi.ListaTiposResponse EndListaTipos(System.IAsyncResult result);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento ListaSituacaoResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaSituacao", ReplyAction="*")]
        ProjetoClientesWeb.ClienteApi.ListaSituacaoResponse ListaSituacao(ProjetoClientesWeb.ClienteApi.ListaSituacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ListaSituacao", ReplyAction="*")]
        System.IAsyncResult BeginListaSituacao(ProjetoClientesWeb.ClienteApi.ListaSituacaoRequest request, System.AsyncCallback callback, object asyncState);
        
        ProjetoClientesWeb.ClienteApi.ListaSituacaoResponse EndListaSituacao(System.IAsyncResult result);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cliente no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insere", ReplyAction="*")]
        ProjetoClientesWeb.ClienteApi.InsereResponse Insere(ProjetoClientesWeb.ClienteApi.InsereRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Insere", ReplyAction="*")]
        System.IAsyncResult BeginInsere(ProjetoClientesWeb.ClienteApi.InsereRequest request, System.AsyncCallback callback, object asyncState);
        
        ProjetoClientesWeb.ClienteApi.InsereResponse EndInsere(System.IAsyncResult result);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cliente no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Altere", ReplyAction="*")]
        ProjetoClientesWeb.ClienteApi.AltereResponse Altere(ProjetoClientesWeb.ClienteApi.AltereRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Altere", ReplyAction="*")]
        System.IAsyncResult BeginAltere(ProjetoClientesWeb.ClienteApi.AltereRequest request, System.AsyncCallback callback, object asyncState);
        
        ProjetoClientesWeb.ClienteApi.AltereResponse EndAltere(System.IAsyncResult result);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento cliente no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        ProjetoClientesWeb.ClienteApi.DeleteResponse Delete(ProjetoClientesWeb.ClienteApi.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.IAsyncResult BeginDelete(ProjetoClientesWeb.ClienteApi.DeleteRequest request, System.AsyncCallback callback, object asyncState);
        
        ProjetoClientesWeb.ClienteApi.DeleteResponse EndDelete(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Lista", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.ListaRequestBody Body;
        
        public ListaRequest() {
        }
        
        public ListaRequest(ProjetoClientesWeb.ClienteApi.ListaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaRequestBody {
        
        public ListaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.ListaResponseBody Body;
        
        public ListaResponse() {
        }
        
        public ListaResponse(ProjetoClientesWeb.ClienteApi.ListaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjetoClientesWeb.ClienteApi.Cliente[] ListaResult;
        
        public ListaResponseBody() {
        }
        
        public ListaResponseBody(ProjetoClientesWeb.ClienteApi.Cliente[] ListaResult) {
            this.ListaResult = ListaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUnicaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUnica", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.ListaUnicaRequestBody Body;
        
        public ListaUnicaRequest() {
        }
        
        public ListaUnicaRequest(ProjetoClientesWeb.ClienteApi.ListaUnicaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaUnicaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cpfCli;
        
        public ListaUnicaRequestBody() {
        }
        
        public ListaUnicaRequestBody(string cpfCli) {
            this.cpfCli = cpfCli;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUnicaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUnicaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.ListaUnicaResponseBody Body;
        
        public ListaUnicaResponse() {
        }
        
        public ListaUnicaResponse(ProjetoClientesWeb.ClienteApi.ListaUnicaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaUnicaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjetoClientesWeb.ClienteApi.Cliente ListaUnicaResult;
        
        public ListaUnicaResponseBody() {
        }
        
        public ListaUnicaResponseBody(ProjetoClientesWeb.ClienteApi.Cliente ListaUnicaResult) {
            this.ListaUnicaResult = ListaUnicaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaTiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaTipos", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.ListaTiposRequestBody Body;
        
        public ListaTiposRequest() {
        }
        
        public ListaTiposRequest(ProjetoClientesWeb.ClienteApi.ListaTiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaTiposRequestBody {
        
        public ListaTiposRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaTiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaTiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.ListaTiposResponseBody Body;
        
        public ListaTiposResponse() {
        }
        
        public ListaTiposResponse(ProjetoClientesWeb.ClienteApi.ListaTiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaTiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjetoClientesWeb.ClienteApi.Tipo_Cliente[] ListaTiposResult;
        
        public ListaTiposResponseBody() {
        }
        
        public ListaTiposResponseBody(ProjetoClientesWeb.ClienteApi.Tipo_Cliente[] ListaTiposResult) {
            this.ListaTiposResult = ListaTiposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaSituacaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaSituacao", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.ListaSituacaoRequestBody Body;
        
        public ListaSituacaoRequest() {
        }
        
        public ListaSituacaoRequest(ProjetoClientesWeb.ClienteApi.ListaSituacaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaSituacaoRequestBody {
        
        public ListaSituacaoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaSituacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaSituacaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.ListaSituacaoResponseBody Body;
        
        public ListaSituacaoResponse() {
        }
        
        public ListaSituacaoResponse(ProjetoClientesWeb.ClienteApi.ListaSituacaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaSituacaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjetoClientesWeb.ClienteApi.Situacao_Cliente[] ListaSituacaoResult;
        
        public ListaSituacaoResponseBody() {
        }
        
        public ListaSituacaoResponseBody(ProjetoClientesWeb.ClienteApi.Situacao_Cliente[] ListaSituacaoResult) {
            this.ListaSituacaoResult = ListaSituacaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsereRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insere", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.InsereRequestBody Body;
        
        public InsereRequest() {
        }
        
        public InsereRequest(ProjetoClientesWeb.ClienteApi.InsereRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsereRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjetoClientesWeb.ClienteApi.Cliente cliente;
        
        public InsereRequestBody() {
        }
        
        public InsereRequestBody(ProjetoClientesWeb.ClienteApi.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsereResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsereResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.InsereResponseBody Body;
        
        public InsereResponse() {
        }
        
        public InsereResponse(ProjetoClientesWeb.ClienteApi.InsereResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsereResponseBody {
        
        public InsereResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltereRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Altere", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.AltereRequestBody Body;
        
        public AltereRequest() {
        }
        
        public AltereRequest(ProjetoClientesWeb.ClienteApi.AltereRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AltereRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjetoClientesWeb.ClienteApi.Cliente cliente;
        
        public AltereRequestBody() {
        }
        
        public AltereRequestBody(ProjetoClientesWeb.ClienteApi.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltereResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltereResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.AltereResponseBody Body;
        
        public AltereResponse() {
        }
        
        public AltereResponse(ProjetoClientesWeb.ClienteApi.AltereResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AltereResponseBody {
        
        public AltereResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(ProjetoClientesWeb.ClienteApi.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjetoClientesWeb.ClienteApi.Cliente cliente;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(ProjetoClientesWeb.ClienteApi.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjetoClientesWeb.ClienteApi.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(ProjetoClientesWeb.ClienteApi.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteResponseBody {
        
        public DeleteResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CadastroSoapChannel : ProjetoClientesWeb.ClienteApi.CadastroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ProjetoClientesWeb.ClienteApi.Cliente[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ProjetoClientesWeb.ClienteApi.Cliente[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaUnicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListaUnicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ProjetoClientesWeb.ClienteApi.Cliente Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ProjetoClientesWeb.ClienteApi.Cliente)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaTiposCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListaTiposCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ProjetoClientesWeb.ClienteApi.Tipo_Cliente[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ProjetoClientesWeb.ClienteApi.Tipo_Cliente[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaSituacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListaSituacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ProjetoClientesWeb.ClienteApi.Situacao_Cliente[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ProjetoClientesWeb.ClienteApi.Situacao_Cliente[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CadastroSoapClient : System.ServiceModel.ClientBase<ProjetoClientesWeb.ClienteApi.CadastroSoap>, ProjetoClientesWeb.ClienteApi.CadastroSoap {
        
        private BeginOperationDelegate onBeginListaDelegate;
        
        private EndOperationDelegate onEndListaDelegate;
        
        private System.Threading.SendOrPostCallback onListaCompletedDelegate;
        
        private BeginOperationDelegate onBeginListaUnicaDelegate;
        
        private EndOperationDelegate onEndListaUnicaDelegate;
        
        private System.Threading.SendOrPostCallback onListaUnicaCompletedDelegate;
        
        private BeginOperationDelegate onBeginListaTiposDelegate;
        
        private EndOperationDelegate onEndListaTiposDelegate;
        
        private System.Threading.SendOrPostCallback onListaTiposCompletedDelegate;
        
        private BeginOperationDelegate onBeginListaSituacaoDelegate;
        
        private EndOperationDelegate onEndListaSituacaoDelegate;
        
        private System.Threading.SendOrPostCallback onListaSituacaoCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsereDelegate;
        
        private EndOperationDelegate onEndInsereDelegate;
        
        private System.Threading.SendOrPostCallback onInsereCompletedDelegate;
        
        private BeginOperationDelegate onBeginAltereDelegate;
        
        private EndOperationDelegate onEndAltereDelegate;
        
        private System.Threading.SendOrPostCallback onAltereCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        public CadastroSoapClient() {
        }
        
        public CadastroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CadastroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadastroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadastroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ListaCompletedEventArgs> ListaCompleted;
        
        public event System.EventHandler<ListaUnicaCompletedEventArgs> ListaUnicaCompleted;
        
        public event System.EventHandler<ListaTiposCompletedEventArgs> ListaTiposCompleted;
        
        public event System.EventHandler<ListaSituacaoCompletedEventArgs> ListaSituacaoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InsereCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AltereCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.ListaResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.Lista(ProjetoClientesWeb.ClienteApi.ListaRequest request) {
            return base.Channel.Lista(request);
        }
        
        public ProjetoClientesWeb.ClienteApi.Cliente[] Lista() {
            ProjetoClientesWeb.ClienteApi.ListaRequest inValue = new ProjetoClientesWeb.ClienteApi.ListaRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.ListaRequestBody();
            ProjetoClientesWeb.ClienteApi.ListaResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).Lista(inValue);
            return retVal.Body.ListaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ProjetoClientesWeb.ClienteApi.CadastroSoap.BeginLista(ProjetoClientesWeb.ClienteApi.ListaRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLista(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLista(System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.ListaRequest inValue = new ProjetoClientesWeb.ClienteApi.ListaRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.ListaRequestBody();
            return ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).BeginLista(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.ListaResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.EndLista(System.IAsyncResult result) {
            return base.Channel.EndLista(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ProjetoClientesWeb.ClienteApi.Cliente[] EndLista(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.ListaResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).EndLista(result);
            return retVal.Body.ListaResult;
        }
        
        private System.IAsyncResult OnBeginLista(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginLista(callback, asyncState);
        }
        
        private object[] OnEndLista(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.Cliente[] retVal = this.EndLista(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListaCompleted(object state) {
            if ((this.ListaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListaCompleted(this, new ListaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListaAsync() {
            this.ListaAsync(null);
        }
        
        public void ListaAsync(object userState) {
            if ((this.onBeginListaDelegate == null)) {
                this.onBeginListaDelegate = new BeginOperationDelegate(this.OnBeginLista);
            }
            if ((this.onEndListaDelegate == null)) {
                this.onEndListaDelegate = new EndOperationDelegate(this.OnEndLista);
            }
            if ((this.onListaCompletedDelegate == null)) {
                this.onListaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListaCompleted);
            }
            base.InvokeAsync(this.onBeginListaDelegate, null, this.onEndListaDelegate, this.onListaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.ListaUnicaResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.ListaUnica(ProjetoClientesWeb.ClienteApi.ListaUnicaRequest request) {
            return base.Channel.ListaUnica(request);
        }
        
        public ProjetoClientesWeb.ClienteApi.Cliente ListaUnica(string cpfCli) {
            ProjetoClientesWeb.ClienteApi.ListaUnicaRequest inValue = new ProjetoClientesWeb.ClienteApi.ListaUnicaRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.ListaUnicaRequestBody();
            inValue.Body.cpfCli = cpfCli;
            ProjetoClientesWeb.ClienteApi.ListaUnicaResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).ListaUnica(inValue);
            return retVal.Body.ListaUnicaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ProjetoClientesWeb.ClienteApi.CadastroSoap.BeginListaUnica(ProjetoClientesWeb.ClienteApi.ListaUnicaRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListaUnica(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListaUnica(string cpfCli, System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.ListaUnicaRequest inValue = new ProjetoClientesWeb.ClienteApi.ListaUnicaRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.ListaUnicaRequestBody();
            inValue.Body.cpfCli = cpfCli;
            return ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).BeginListaUnica(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.ListaUnicaResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.EndListaUnica(System.IAsyncResult result) {
            return base.Channel.EndListaUnica(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ProjetoClientesWeb.ClienteApi.Cliente EndListaUnica(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.ListaUnicaResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).EndListaUnica(result);
            return retVal.Body.ListaUnicaResult;
        }
        
        private System.IAsyncResult OnBeginListaUnica(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string cpfCli = ((string)(inValues[0]));
            return this.BeginListaUnica(cpfCli, callback, asyncState);
        }
        
        private object[] OnEndListaUnica(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.Cliente retVal = this.EndListaUnica(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListaUnicaCompleted(object state) {
            if ((this.ListaUnicaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListaUnicaCompleted(this, new ListaUnicaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListaUnicaAsync(string cpfCli) {
            this.ListaUnicaAsync(cpfCli, null);
        }
        
        public void ListaUnicaAsync(string cpfCli, object userState) {
            if ((this.onBeginListaUnicaDelegate == null)) {
                this.onBeginListaUnicaDelegate = new BeginOperationDelegate(this.OnBeginListaUnica);
            }
            if ((this.onEndListaUnicaDelegate == null)) {
                this.onEndListaUnicaDelegate = new EndOperationDelegate(this.OnEndListaUnica);
            }
            if ((this.onListaUnicaCompletedDelegate == null)) {
                this.onListaUnicaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListaUnicaCompleted);
            }
            base.InvokeAsync(this.onBeginListaUnicaDelegate, new object[] {
                        cpfCli}, this.onEndListaUnicaDelegate, this.onListaUnicaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.ListaTiposResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.ListaTipos(ProjetoClientesWeb.ClienteApi.ListaTiposRequest request) {
            return base.Channel.ListaTipos(request);
        }
        
        public ProjetoClientesWeb.ClienteApi.Tipo_Cliente[] ListaTipos() {
            ProjetoClientesWeb.ClienteApi.ListaTiposRequest inValue = new ProjetoClientesWeb.ClienteApi.ListaTiposRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.ListaTiposRequestBody();
            ProjetoClientesWeb.ClienteApi.ListaTiposResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).ListaTipos(inValue);
            return retVal.Body.ListaTiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ProjetoClientesWeb.ClienteApi.CadastroSoap.BeginListaTipos(ProjetoClientesWeb.ClienteApi.ListaTiposRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListaTipos(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListaTipos(System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.ListaTiposRequest inValue = new ProjetoClientesWeb.ClienteApi.ListaTiposRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.ListaTiposRequestBody();
            return ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).BeginListaTipos(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.ListaTiposResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.EndListaTipos(System.IAsyncResult result) {
            return base.Channel.EndListaTipos(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ProjetoClientesWeb.ClienteApi.Tipo_Cliente[] EndListaTipos(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.ListaTiposResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).EndListaTipos(result);
            return retVal.Body.ListaTiposResult;
        }
        
        private System.IAsyncResult OnBeginListaTipos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginListaTipos(callback, asyncState);
        }
        
        private object[] OnEndListaTipos(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.Tipo_Cliente[] retVal = this.EndListaTipos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListaTiposCompleted(object state) {
            if ((this.ListaTiposCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListaTiposCompleted(this, new ListaTiposCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListaTiposAsync() {
            this.ListaTiposAsync(null);
        }
        
        public void ListaTiposAsync(object userState) {
            if ((this.onBeginListaTiposDelegate == null)) {
                this.onBeginListaTiposDelegate = new BeginOperationDelegate(this.OnBeginListaTipos);
            }
            if ((this.onEndListaTiposDelegate == null)) {
                this.onEndListaTiposDelegate = new EndOperationDelegate(this.OnEndListaTipos);
            }
            if ((this.onListaTiposCompletedDelegate == null)) {
                this.onListaTiposCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListaTiposCompleted);
            }
            base.InvokeAsync(this.onBeginListaTiposDelegate, null, this.onEndListaTiposDelegate, this.onListaTiposCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.ListaSituacaoResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.ListaSituacao(ProjetoClientesWeb.ClienteApi.ListaSituacaoRequest request) {
            return base.Channel.ListaSituacao(request);
        }
        
        public ProjetoClientesWeb.ClienteApi.Situacao_Cliente[] ListaSituacao() {
            ProjetoClientesWeb.ClienteApi.ListaSituacaoRequest inValue = new ProjetoClientesWeb.ClienteApi.ListaSituacaoRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.ListaSituacaoRequestBody();
            ProjetoClientesWeb.ClienteApi.ListaSituacaoResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).ListaSituacao(inValue);
            return retVal.Body.ListaSituacaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ProjetoClientesWeb.ClienteApi.CadastroSoap.BeginListaSituacao(ProjetoClientesWeb.ClienteApi.ListaSituacaoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListaSituacao(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginListaSituacao(System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.ListaSituacaoRequest inValue = new ProjetoClientesWeb.ClienteApi.ListaSituacaoRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.ListaSituacaoRequestBody();
            return ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).BeginListaSituacao(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.ListaSituacaoResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.EndListaSituacao(System.IAsyncResult result) {
            return base.Channel.EndListaSituacao(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ProjetoClientesWeb.ClienteApi.Situacao_Cliente[] EndListaSituacao(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.ListaSituacaoResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).EndListaSituacao(result);
            return retVal.Body.ListaSituacaoResult;
        }
        
        private System.IAsyncResult OnBeginListaSituacao(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginListaSituacao(callback, asyncState);
        }
        
        private object[] OnEndListaSituacao(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.Situacao_Cliente[] retVal = this.EndListaSituacao(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListaSituacaoCompleted(object state) {
            if ((this.ListaSituacaoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListaSituacaoCompleted(this, new ListaSituacaoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListaSituacaoAsync() {
            this.ListaSituacaoAsync(null);
        }
        
        public void ListaSituacaoAsync(object userState) {
            if ((this.onBeginListaSituacaoDelegate == null)) {
                this.onBeginListaSituacaoDelegate = new BeginOperationDelegate(this.OnBeginListaSituacao);
            }
            if ((this.onEndListaSituacaoDelegate == null)) {
                this.onEndListaSituacaoDelegate = new EndOperationDelegate(this.OnEndListaSituacao);
            }
            if ((this.onListaSituacaoCompletedDelegate == null)) {
                this.onListaSituacaoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListaSituacaoCompleted);
            }
            base.InvokeAsync(this.onBeginListaSituacaoDelegate, null, this.onEndListaSituacaoDelegate, this.onListaSituacaoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.InsereResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.Insere(ProjetoClientesWeb.ClienteApi.InsereRequest request) {
            return base.Channel.Insere(request);
        }
        
        public void Insere(ProjetoClientesWeb.ClienteApi.Cliente cliente) {
            ProjetoClientesWeb.ClienteApi.InsereRequest inValue = new ProjetoClientesWeb.ClienteApi.InsereRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.InsereRequestBody();
            inValue.Body.cliente = cliente;
            ProjetoClientesWeb.ClienteApi.InsereResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).Insere(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ProjetoClientesWeb.ClienteApi.CadastroSoap.BeginInsere(ProjetoClientesWeb.ClienteApi.InsereRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsere(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginInsere(ProjetoClientesWeb.ClienteApi.Cliente cliente, System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.InsereRequest inValue = new ProjetoClientesWeb.ClienteApi.InsereRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.InsereRequestBody();
            inValue.Body.cliente = cliente;
            return ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).BeginInsere(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.InsereResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.EndInsere(System.IAsyncResult result) {
            return base.Channel.EndInsere(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndInsere(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.InsereResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).EndInsere(result);
        }
        
        private System.IAsyncResult OnBeginInsere(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.Cliente cliente = ((ProjetoClientesWeb.ClienteApi.Cliente)(inValues[0]));
            return this.BeginInsere(cliente, callback, asyncState);
        }
        
        private object[] OnEndInsere(System.IAsyncResult result) {
            this.EndInsere(result);
            return null;
        }
        
        private void OnInsereCompleted(object state) {
            if ((this.InsereCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsereCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsereAsync(ProjetoClientesWeb.ClienteApi.Cliente cliente) {
            this.InsereAsync(cliente, null);
        }
        
        public void InsereAsync(ProjetoClientesWeb.ClienteApi.Cliente cliente, object userState) {
            if ((this.onBeginInsereDelegate == null)) {
                this.onBeginInsereDelegate = new BeginOperationDelegate(this.OnBeginInsere);
            }
            if ((this.onEndInsereDelegate == null)) {
                this.onEndInsereDelegate = new EndOperationDelegate(this.OnEndInsere);
            }
            if ((this.onInsereCompletedDelegate == null)) {
                this.onInsereCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsereCompleted);
            }
            base.InvokeAsync(this.onBeginInsereDelegate, new object[] {
                        cliente}, this.onEndInsereDelegate, this.onInsereCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.AltereResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.Altere(ProjetoClientesWeb.ClienteApi.AltereRequest request) {
            return base.Channel.Altere(request);
        }
        
        public void Altere(ProjetoClientesWeb.ClienteApi.Cliente cliente) {
            ProjetoClientesWeb.ClienteApi.AltereRequest inValue = new ProjetoClientesWeb.ClienteApi.AltereRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.AltereRequestBody();
            inValue.Body.cliente = cliente;
            ProjetoClientesWeb.ClienteApi.AltereResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).Altere(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ProjetoClientesWeb.ClienteApi.CadastroSoap.BeginAltere(ProjetoClientesWeb.ClienteApi.AltereRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAltere(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAltere(ProjetoClientesWeb.ClienteApi.Cliente cliente, System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.AltereRequest inValue = new ProjetoClientesWeb.ClienteApi.AltereRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.AltereRequestBody();
            inValue.Body.cliente = cliente;
            return ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).BeginAltere(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.AltereResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.EndAltere(System.IAsyncResult result) {
            return base.Channel.EndAltere(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAltere(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.AltereResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).EndAltere(result);
        }
        
        private System.IAsyncResult OnBeginAltere(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.Cliente cliente = ((ProjetoClientesWeb.ClienteApi.Cliente)(inValues[0]));
            return this.BeginAltere(cliente, callback, asyncState);
        }
        
        private object[] OnEndAltere(System.IAsyncResult result) {
            this.EndAltere(result);
            return null;
        }
        
        private void OnAltereCompleted(object state) {
            if ((this.AltereCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AltereCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AltereAsync(ProjetoClientesWeb.ClienteApi.Cliente cliente) {
            this.AltereAsync(cliente, null);
        }
        
        public void AltereAsync(ProjetoClientesWeb.ClienteApi.Cliente cliente, object userState) {
            if ((this.onBeginAltereDelegate == null)) {
                this.onBeginAltereDelegate = new BeginOperationDelegate(this.OnBeginAltere);
            }
            if ((this.onEndAltereDelegate == null)) {
                this.onEndAltereDelegate = new EndOperationDelegate(this.OnEndAltere);
            }
            if ((this.onAltereCompletedDelegate == null)) {
                this.onAltereCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAltereCompleted);
            }
            base.InvokeAsync(this.onBeginAltereDelegate, new object[] {
                        cliente}, this.onEndAltereDelegate, this.onAltereCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.DeleteResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.Delete(ProjetoClientesWeb.ClienteApi.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public void Delete(ProjetoClientesWeb.ClienteApi.Cliente cliente) {
            ProjetoClientesWeb.ClienteApi.DeleteRequest inValue = new ProjetoClientesWeb.ClienteApi.DeleteRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.DeleteRequestBody();
            inValue.Body.cliente = cliente;
            ProjetoClientesWeb.ClienteApi.DeleteResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ProjetoClientesWeb.ClienteApi.CadastroSoap.BeginDelete(ProjetoClientesWeb.ClienteApi.DeleteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDelete(ProjetoClientesWeb.ClienteApi.Cliente cliente, System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.DeleteRequest inValue = new ProjetoClientesWeb.ClienteApi.DeleteRequest();
            inValue.Body = new ProjetoClientesWeb.ClienteApi.DeleteRequestBody();
            inValue.Body.cliente = cliente;
            return ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).BeginDelete(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjetoClientesWeb.ClienteApi.DeleteResponse ProjetoClientesWeb.ClienteApi.CadastroSoap.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDelete(System.IAsyncResult result) {
            ProjetoClientesWeb.ClienteApi.DeleteResponse retVal = ((ProjetoClientesWeb.ClienteApi.CadastroSoap)(this)).EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ProjetoClientesWeb.ClienteApi.Cliente cliente = ((ProjetoClientesWeb.ClienteApi.Cliente)(inValues[0]));
            return this.BeginDelete(cliente, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            this.EndDelete(result);
            return null;
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(ProjetoClientesWeb.ClienteApi.Cliente cliente) {
            this.DeleteAsync(cliente, null);
        }
        
        public void DeleteAsync(ProjetoClientesWeb.ClienteApi.Cliente cliente, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        cliente}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
    }
}
